migrateup:
	migrate -path ./migrations -database "postgres://deepaljain:postgres@localhost:5432/user_db?sslmode=disable" up

migratedown:
	migrate -path ./migrations -database "postgres://deepaljain:postgres@localhost:5432/user_db?sslmode=disable" down